@baseUrl = http://localhost:3001
@token = {{authenticateUser.response.body.token}}

### Create a new user
# @name createUser

POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Felippe Jaqson Chemello",
    "email": "felippe@codestack.me",
    "password": "123456"
}

### Authenticate user
# @name authenticateUser

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "felippe@codestack.me",
    "password": "123456"
}

### Get info from authenticated user
@name = getUser

GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}